name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'  # Recommended to use an LTS version

    - name: Install dependencies
      run: npm ci

    - name: Build project (if present)
      run: npm run build --if-present

    - name: Run tests
      run: npm test

    - name: Upload error logs (if applicable)
      if: failure()
      run: |
        echo "Uploading error logs"
        cat /tmp/your_log_file.log  # You can replace this with any relevant log location
